# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
import numpy as np

In [10]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import random
x= [random.randint(1,20) for x in range(5) for y in range(5)]
x = np.array(x).reshape(5,5)
x[:,2]=1
print(x)

arr1= np.random.randint(1, 21, size=(5, 5))

# Replace all elements in the third column (index 2) with 1
arr1[:, 2] = 1
print(arr1)

arr = np.arange(1, 17).reshape(4, 4)
np.fill_diagonal(arr, 0)
print(arr)

[[ 6  5  1 18  7]
 [11  4  1  2  9]
 [ 8 12  1 15 12]
 [ 1  2  1  5 17]
 [ 1  9  1  3 15]]
[[14  5  1 20 17]
 [ 1 18  1  2 14]
 [17 20  1  1 17]
 [ 9  1  1  8  5]
 [ 9 12  1 10 15]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [28]:

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
# # 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
z=np.arange(1,37).reshape(6,6)
print(z[2:5,1:4])
a=np.random.randint(0,10,size=(5,5))
print(a)
print(a[0,0:5])
print(a[0:5,0])
print(a[0:5,4])
print(a[4,0:5])

[[14 15 16]
 [20 21 22]
 [26 27 28]]
[[1 1 5 7 4]
 [4 7 6 2 5]
 [2 6 3 6 4]
 [9 0 3 0 8]
 [9 0 9 9 4]]
[1 1 5 7 4]
[1 4 2 9 9]
[4 5 4 8 4]
[9 0 9 9 4]


In [30]:

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

a=np.random.randint(0,100,size=(3,4))
b=np.random.randint(0,100,size=(3,4))
print(a+b)
print(a-b)
print(a*b)
print(a/b)

# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr=np.arange(1,17).reshape(4,4)
print(arr.sum(axis=0))
print(arr.sum(axis=1))

[[106 129  16  61]
 [ 88 149  72  18]
 [117 111  51  41]]
[[-42  57  14 -31]
 [ 38 -11  50 -18]
 [-33 -69  31  29]]
[[2368 3348   15  690]
 [1575 5520  671    0]
 [3150 1890  410  210]]
[[ 0.43243243  2.58333333 15.          0.32608696]
 [ 2.52        0.8625      5.54545455  0.        ]
 [ 0.56        0.23333333  4.1         5.83333333]]
[28 32 36 40]
[10 26 42 58]


In [ ]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

arr=np.random.randint(1,50,size=(5,5))

# 2. Compute the mean, median, standard deviation, and variance of the array.
mean_value = np.mean(arr)
median_value = np.median(arr)
std_deviation = np.std(arr)
variance_value = np.var(arr)

print(arr)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_deviation)
print("Variance:", variance_value)

# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

arr1 = np.arange(1,9).reshape(3,3)
print(arr1)
 

[[33 30 22 14 21]
 [30  5 14 12 17]
 [20 23 38 22  3]
 [41 31 36 37 43]
 [ 3  3 47 44 47]]

Mean: 25.44
Median: 23.0
Standard Deviation: 13.96876515659133
Variance: 195.1264


In [42]:
# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

x = np.random.randint(1,50,size=(3,3))
y = np.random.randint(1,50,size=(3,))
print(x)
print(y)
print(x+y)

# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
x1 = np.random.randint(1,50,size=(4,4))
y1 = np.random.randint(1,50,size=(4,))
print(x1)
print(y1)
print(x1-y1)

[[19 12  9]
 [ 9 42 11]
 [19  1 27]]
[37 37 24]
[[56 49 33]
 [46 79 35]
 [56 38 51]]
[[32  7 32 40]
 [ 5 10 30 36]
 [40 48 33 21]
 [25 31 29 38]]
[22 35 40 45]
[[ 10 -28  -8  -5]
 [-17 -25 -10  -9]
 [ 18  13  -7 -24]
 [  3  -4 -11  -7]]


In [47]:
# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

z = np.arange(1, 10).reshape(3, 3)
print("Matrix Z:\n", z)

# Determinant
det_z = np.linalg.det(z)
print("Determinant of Z:", det_z)

# Inverse (check if matrix is invertible)
if det_z != 0:
    inv_z = np.linalg.inv(z)
    print("Inverse of Z:\n", inv_z)
else:
    print("Matrix Z is singular and cannot be inverted.")

# Eigenvalues
eigvals_z = np.linalg.eigvals(z)
print("Eigenvalues of Z:", eigvals_z)

# 2. Create two matrices and perform matrix multiplication
x = np.arange(1, 7).reshape(2, 3)   # shape (2, 3)
y = np.arange(6, 12).reshape(3, 2)  # shape (3, 2)

# Matrix multiplication
product = x @ y
print("Matrix multiplication result (x @ y):\n", product)

Matrix Z:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of Z: 0.0
Matrix Z is singular and cannot be inverted.
Eigenvalues of Z: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Matrix multiplication result (x @ y):
 [[ 52  58]
 [124 139]]


In [53]:
# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

x = np.arange(1,10).reshape(1,9)
y=x.reshape(9,1)
print(x)
print(y)

z = np.random.randint(1,50,size=(5,5))
print(z)
a=z.flatten()
print(a)
z=a.reshape(5,5)
print(z)


[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[24 44 29 19 36]
 [19 27 38 11 20]
 [ 8 39 25  1 44]
 [19  8 21 45 40]
 [ 6 36 27 21 24]]
[24 44 29 19 36 19 27 38 11 20  8 39 25  1 44 19  8 21 45 40  6 36 27 21
 24]
[[24 44 29 19 36]
 [19 27 38 11 20]
 [ 8 39 25  1 44]
 [19  8 21 45 40]
 [ 6 36 27 21 24]]


In [54]:
import numpy as np

# Task 1: Create (5,5) array and extract corners using fancy indexing
x = np.random.randint(1, 50, size=(5, 5))
print("Original (5x5) array:\n", x)

# Top-left and top-right
print("Top-left and Top-right corners:", x[[0, 0], [0, 4]])

# Bottom-left and bottom-right
print("Bottom-left and Bottom-right corners:", x[[4, 4], [0, 4]])

# Task 2: Boolean indexing on (4,4) array
y = np.random.randint(1, 50, size=(4, 4))
print("\nOriginal (4x4) array:\n", y)

# Set all elements > 10 to 10
y[y > 10] = 10

# Print modified array
print("\nModified array (values > 10 set to 10):\n", y)


Original (5x5) array:
 [[14 20  5 18 48]
 [ 2 17  1 13  3]
 [27 39 34 29  2]
 [ 4 30 40 41 19]
 [ 9 32 11 32 21]]
Top-left and Top-right corners: [14 48]
Bottom-left and Bottom-right corners: [ 9 21]

Original (4x4) array:
 [[ 4  5 17 49]
 [32 13 45 21]
 [33  7  4  1]
 [ 5  8 11 38]]

Modified array (values > 10 set to 10):
 [[ 4  5 10 10]
 [10 10 10 10]
 [10  7  4  1]
 [ 5  8 10 10]]


In [ ]:
dtype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 30, 75.0),
    ('Charlie', 22, 68.2),
    ('Diana', 28, 60.0)
], dtype=dtype)
print("Original array:\n", data)

sorted_data = np.sort(data, order='age')
print("\nArray sorted by age:\n", sorted_data)

dtype1 = [('x', 'i4'), ('y', 'i4')]
data1 = np.array([(1, 2),(3, 4),(5, 6),(7, 8)], dtype=dtype1)

coords = np.stack((data1['x'], data1['y']), axis=1)

distances = np.linalg.norm(coords[:, None] - coords, axis=2)
print("\nEuclidean distances:\n", distances)

Original array:
 [('Alice', 25, 55.5) ('Bob', 30, 75. ) ('Charlie', 22, 68.2)
 ('Diana', 28, 60. )]

Array sorted by age:
 [('Charlie', 22, 68.2) ('Alice', 25, 55.5) ('Diana', 28, 60. )
 ('Bob', 30, 75. )]

Euclidean distances:
 [[0.         2.82842712 5.65685425 8.48528137]
 [2.82842712 0.         2.82842712 5.65685425]
 [5.65685425 2.82842712 0.         2.82842712]
 [8.48528137 5.65685425 2.82842712 0.        ]]


In [60]:
# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

import numpy.ma as ma

# Task 1: Mask elements > 10 and compute sum of unmasked
arr1 = np.random.randint(1, 21, size=(4, 4))
masked_arr1 = ma.masked_greater(arr1, 10)

print("Original (4x4) array:\n", arr1)
print("\nMasked array (values > 10 are masked):\n", masked_arr1)
print("\nSum of unmasked elements:", masked_arr1.sum())

# Task 2: Mask diagonal and replace masked values with mean of unmasked
arr2 = np.random.randint(1, 21, size=(3, 3))
masked_arr2 = ma.array(arr2, mask=np.eye(3, dtype=bool))

print("\nOriginal (3x3) array:\n", arr2)
print("\nMasked array (diagonal masked):\n", masked_arr2)

# Compute mean of unmasked elements
mean_unmasked = masked_arr2.mean()

# Fill masked values with the mean
filled_arr2 = masked_arr2.filled(mean_unmasked)
print("\nMasked elements replaced with mean of unmasked elements:\n", filled_arr2)

Original (4x4) array:
 [[ 6  1 14 13]
 [11 20  3  8]
 [12 18 14 13]
 [20 19 11  1]]

Masked array (values > 10 are masked):
 [[6 1 -- --]
 [-- -- 3 8]
 [-- -- -- --]
 [-- -- -- 1]]

Sum of unmasked elements: 19

Original (3x3) array:
 [[19 10 12]
 [ 7  1  2]
 [14 11  7]]

Masked array (diagonal masked):
 [[-- 10 12]
 [7 -- 2]
 [14 11 --]]

Masked elements replaced with mean of unmasked elements:
 [[ 9 10 12]
 [ 7  9  2]
 [14 11  9]]
